# Generated by Django 3.2.12 on 2023-04-14 19:33

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=75, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('age', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=app.models.upload_to, verbose_name='Image')),
                ('upi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=75, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
    ]
