# Generated by Django 3.2.12 on 2023-04-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='upi',
            field=models.CharField(max_length=50),
        ),
    ]
